- name: Ensure /etc/hosts contains entry pointing to the Traefik instance
  hosts: localhost
  tasks:
    - name: Configure /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        backup: true
        dest: /etc/hosts
        regexp: ".*{{ domain_name }}$"
        line: "{{ groups['traefik'][0] }} {{ domain_name }}"
        state: "{{ etchosts_state | default('present') }}"
