---
- name: Manage SSH known_hosts
  hosts: localhost
  connection: local
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts_state: "{{ ssh_knownhosts_state | default('present') }}"

  tasks:
    - name: For each host, scan for its ssh public key
      ansible.builtin.shell: "{{ ssh_known_hosts_command }} {{ item }}"
      with_items: "{{ hostvars }}"
      register: ssh_known_host_results
      ignore_errors: yes

    - name: Manage the public key in the '{{ ssh_known_hosts_file }}'
      ansible.builtin.known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout if ssh_known_hosts_state == 'present' else '' }}"
        path: "{{ ssh_known_hosts_file }}"
        state: "{{ ssh_known_hosts_state }}"
      with_items: "{{ ssh_known_host_results.results }}"
