- name: Apply package updates to all hosts (except management_vm)
  # Skip management_vm as it's the jump host so we don't want it restarting
  hosts: all:!localhost:!management_vm
  roles:
    - role: packages_update

- name: Apply package updates to management_vm
  hosts: management_vm
  roles:
    - role: packages_update
