name: accelerator
version: "1.0.0"

profile: "trino_catalog"

flags:
  require_certificate_validation: True

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  # The start date of equipment downtime records from Opralog
  opralog_epoch_date: "2017-04-25"

models:
  +file_format: parquet
  +materialized: table
  accelerator:
    # The full schema name of the final tables is "{target_schema}_"{custom_schema}"
    #   - 'target_schema' is defined in profiles.yml
    #   - 'custom_schema' is defined for each collection of models below
    # See https://docs.getdbt.com/docs/build/custom-schemas
    staging:
      +schema: staging
      +materialized: view
    operations:
      +schema: operations
