---
- name: Configure preequisites for MSSQL server
  hosts: opralogdb
  roles:
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker
      become: true

- name: Run Opralog
  hosts: opralogdb
  vars:
    opralogdb_container_name: opralogdb
    opralogdb_user: "SA"
    opralogdb_passwd: "{{ vault_opralogdb_passwd }}"
    opralogdb_dbname: "LOGBOOK"
    opralogdb_backup_dir: "/staging/opralog/full-backups"
    opralogdb_backup_filename: "LOGBOOK_backup_2024_06_24_183655_2079164.bak"
  tasks:
    - name: Ensure Opralog DB container is running
      become: true
      community.docker.docker_container:
        name: "{{ opralogdb_container_name }}"
        image: mcr.microsoft.com/mssql/server:2019-latest
        state: started
        cleanup: true
        detach: true
        restart: true
        restart_policy: unless-stopped
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "{{ opralogdb_passwd }}"
        published_ports:
          - "{{ opralogdb_port }}:1433"
        volumes:
          - opralogdb_data:/var/opt/mssql
          - "{{ cephfs_mount_mount_path }}/staging:/staging:ro"

    - name: Query existing databases
      community.docker.docker_container_exec:
        container: "{{ opralogdb_container_name }}"
        command: >-
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U {{ opralogdb_user }} -P {{ opralogdb_passwd }} -Q "{{ query }}"
      register: databases
      vars:
        query: "SELECT name FROM master.sys.databases WHERE name = '{{ opralogdb_dbname }}'"

    - name: "Import database backup"
      community.docker.docker_container_exec:
        container: "{{ opralogdb_container_name }}"
        command: >-
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U {{ opralogdb_user }}
          -P {{ opralogdb_passwd }} -Q "{{ backup_restore }}"
      vars:
        backup_restore: >-
          RESTORE DATABASE LOGBOOK FROM DISK = '{{ opralogdb_backup_dir }}/{{ opralogdb_backup_filename }}'
          WITH MOVE '{{ opralogdb_dbname }}_Data' TO '/var/opt/mssql/{{ opralogdb_dbname }}_Data.mdf',
          MOVE '{{ opralogdb_dbname }}_Log' TO '/var/opt/mssql/{{ opralogdb_dbname }}_Log.ldf'
        opralog_db: "{{ databases.stdout_lines | map('trim') | select('==', opralogdb_dbname) }}"
      when: "(opralog_db | length()) == 0"
