---
# image
superset_container_image: ghcr.io/martyngigg/adp-superset-forked:901412e

# common db
superset_metadb_host: "{{ vault_db_host }}"
superset_metadb_port: "{{ vault_db_port }}"
superset_metadb_name: "{{ vault_superset_metadb_name }}"
superset_metadb_user: "{{ vault_superset_metadb_user }}"
superset_metadb_passwd: "{{ vault_superset_metadb_passwd }}"
