---
- name: Provision VMs for Jupyter
  hosts: localhost
  vars:
    openstack_security_group_name: jupyter
    openstack_security_group_description: Ingress to Jupyter ports
    openstack_security_group_rules: |-
     [
     {% for port in (jupyter_notebook_port,)  %}
       {
        "direction": "ingress",
        "ether_type": "IPv4",
        "protocol": "tcp",
        "port_range_min": "{{ port }}",
        "port_range_max": "{{ port }}"
       }
       {% endfor %}
      ]
    openstack_flavor: l3.nano
    openstack_server_name: spark
    openstack_vm_user: ubuntu
    inventory_group: spark
  roles:
    - name: security_group_create
    - name: vm_create

- name: Base VM configuration
  hosts: spark
  roles:
    - name: packages_update
