---
- name: Provision VMs for minio service
  hosts: localhost
  vars:
    openstack_security_group_name: minio
    openstack_security_group_description: Ingress to minio ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: 9000
        port_range_max: 9001
    openstack_flavor: l3.nano
    openstack_server_name: minio
    openstack_vm_user: ubuntu
    inventory_group: minio
  roles:
    - name: security_group_create
    - name: vm_create

- name: Base VM configuration
  hosts: minio
  roles:
    - name: packages_update
