---
# base image name built by superset task
superset_base_image: local/superset
superset_build_path: /build/superset
superset_config_path: /config/superset
superset_git_url: https://github.com/apache/superset/

# app
superset_flask_debug: false
superset_env_name: production
