---
- name: Deploy traefik
  hosts: traefik
  roles:
    - role: base
    - role: docs
      become: true
    - role: traefik

- name: Deploy data services (if required)
  hosts: datastore
  roles:
    - role: base
    - role: postgres
    - role: minio

- name: Deploy Keycloak
  hosts: keycloak
  roles:
    - role: base
    - role: keycloak

- name: Deploy Lakekeeper
  hosts: lakekeeper
  roles:
    - role: base
    - role: lakekeeper

- name: Deploy Trino
  hosts: trino
  roles:
    - base
    - trino

- name: Deploy Superset instances
  hosts: superset_farm
  roles:
    - base
    - superset_farm
