---
- name: Deploy traefik
  hosts: traefik
  roles:
    - role: base
    - role: docs
      become: true
    - role: traefik

- name: Deploy postgres (if required)
  hosts: postgres
  roles:
    - role: base
    - role: postgres

- name: Deploy Keycloak
  hosts: keycloak
  roles:
    - role: base
    - role: keycloak
