version: 2

models:
  - name: cycles
    description: "The ISIS cycle dates, including pre and post user-cycle phases."
  - name: power_consumption
    description: "The total power consumption for ISIS over time"
