---
keycloak_image: quay.io/keycloak/keycloak:26.1.4
keycloak_container_network: keycloak
keycloak_http_port: 8080
keycloak_http_management_port: 9000
keycloak_base_path: /auth
keycloak_bootstrap_admin_passwd: "{{ vault_keycloak_bootstrap_admin_passwd }}"

keycloak_store_port: 5432
keycloak_store_dbname: keycloak
keycloak_store_user: keycloak
keycloak_store_passwd: "{{ vault_keycloak_store_passwd }}"
