---
# See s3.yml to switch between MinIO & Ceph S3 service
minio_data_path: "{{ cephfs_mount_mount_path }}/live/minio/data"
minio_rest_http_port: 9000
minio_rest_https_port: 9000
minio_console_http_port: 9001
minio_console_https_port: 8443
minio_s3_endpoint: "http://{{ groups['minio'][0] }}:{{ minio_rest_http_port }}"
minio_region: eu-west-1
minio_root_user: admin
minio_root_passwd: "{{ vault_minio_root_passwd }}"
minio_access_key_id: "{{ minio_root_user }}"
minio_access_secret: "{{ vault_minio_root_passwd }}"
