---
nessie_image: ghcr.io/projectnessie/nessie:0.103.0
nessie_container_network: nessie
nessie_http_port: 19120
nessie_base_path: /nessie
nessie_iceberg_catalog:
  name: isis
  uri: "https://{{ top_level_domain }}{{ nessie_base_path if nessie_base_path != '/' else '' }}/iceberg/"
  location: s3://prod-warehouse-isis/

nessie_store_port: 5432
nessie_store_dbname: nessiedb
nessie_store_user: nessie
nessie_store_passwd: "{{ vault_nessie_store_passwd }}"
