---
# Vault specifics
vault_secret_prefix_all: "analytics-data-platform/data/all"
vault_secret_prefix_env: "analytics-data-platform/data/{{ deploy_env }}"

# shared
vault_cephfs: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_all + '/cephfs')['data']['data'] }}"
vault_msgraph: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_all + '/msgraph')['data']['data'] }}"
vault_stfc: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_all + '/stfc')['data']['data'] }}"

# environment-specific
vault_keycloak: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_env + '/keycloak')['data']['data'] }}"
vault_keycloak_client_secrets: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_env + '/keycloak_client_secrets')['data']['data'] }}"
vault_elt_opralogweb: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_env + '/opralogweb')['data']['data'] }}"
vault_traefik: "{{ lookup('community.hashi_vault.vault_read', vault_secret_prefix_env + '/traefik')['data']['data'] }}"
