---
# Vault specifics
secrets_prefix_all: "analytics-data-platform/data/all"
secrets_prefix_env: "analytics-data-platform/data/{{ deploy_env }}"

# shared
secrets_cephfs: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_all + '/cephfs')['data']['data'] }}"
secrets_msgraph: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_all + '/msgraph')['data']['data'] }}"
secrets_stfc: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_all + '/stfc')['data']['data'] }}"

# environment-specific
secrets_keycloak: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_env + '/keycloak')['data']['data'] }}"
secrets_keycloak_client_secrets: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_env + '/keycloak_client_secrets')['data']['data'] }}"
secrets_elt_opralogweb: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_env + '/opralogweb')['data']['data'] }}"
secrets_traefik: "{{ lookup('community.hashi_vault.secrets_read', secrets_prefix_env + '/traefik')['data']['data'] }}"
