---
# Vault specifics
secrets_prefix_all: "analytics-data-platform/data/all"
secrets_prefix_env: "analytics-data-platform/data/{{ deploy_env }}"

# shared
secrets_cephfs: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_all + '/cephfs')['data']['data'] }}"
secrets_msgraph: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_all + '/msgraph')['data']['data'] }}"
secrets_stfc: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_all + '/stfc')['data']['data'] }}"
secrets_superset_farm_users_yaml: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_all + '/superset_farm_users_yaml')['data']['data'] }}"
secrets_elt_opralogweb: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_all + '/opralogweb')['data']['data'] }}"

# environment-specific
secrets_certs: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/certs')['data']['data'] }}"
secrets_keycloak: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/keycloak')['data']['data'] }}"
secrets_keycloak_client_secrets: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/keycloak_client_secrets')['data']['data'] }}"
secrets_openfga: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/openfga')['data']['data'] }}"
secrets_lakekeeper: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/lakekeeper')['data']['data'] }}"
secrets_superset_accelerator: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/superset_accelerator')['data']['data'] }}"
secrets_traefik: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/traefik')['data']['data'] }}"
secrets_trino: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/trino')['data']['data'] }}"
secrets_trino_users: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/trino_users')['data']['data'] }}"
