---
spark_vm_flavor: l3.small

spark_controller_port: 7077
spark_controller_ui_port: 8080
spark_controller_ui_https_port: 8445
spark_worker_ports:
  - 42000

spark_reverse_proxy_url: https://{{ top_level_domain }}:{{ spark_controller_ui_https_port }}

# SQL
spark_default_packages:
  - org.apache.hadoop:hadoop-aws:3.3.4
  - org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1
  - org.apache.iceberg:iceberg-aws-bundle:1.6.1
spark_default_sql_exts:
  - org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
