version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/elt-common"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "s3fs"  # https://github.com/ISISNeutronMuon/analytics-data-platform/issues/237
    groups:
      elt-common-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps): "
    cooldown:
      default-days: 7
      semver-major-days: 30

  - package-ecosystem: "pip"
    directories:
      - "/warehouses/facility_ops/transform"
    schedule:
      interval: "monthly"
    groups:
      dbt-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps): "
    cooldown:
      default-days: 7
      semver-major-days: 30

  - package-ecosystem: "pip"
    directories:
      - "/infra/ansible"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "passlib"  # https://github.com/ISISNeutronMuon/analytics-data-platform/issues/313
      - dependency-name: "bcrypt"
    groups:
      ansible-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps): "
    cooldown:
      default-days: 7
      semver-major-days: 30

  - package-ecosystem: "pip"
    directories:
      - "/docs"
    schedule:
      interval: "monthly"
    groups:
      docs-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps): "
    cooldown:
      default-days: 7
      semver-major-days: 30
