# See https://docs.coderabbit.ai/reference/yaml-template for complete reference
language: "en-GB"

reviews:
  profile: "chill"
  high_level_summary: true
  auto_review:
    enabled: true
    # Auto review after every push can be too noisy.
    # To manually request a review, comment
    # - @coderabbitai review # new changes only
    # - @coderabbitai full review # full review from scratch
    auto_incremental_review: false
    drafts: false
  sequence_diagrams: false
  tools:
    gitleaks:
      enabled: true
chat:
  auto_reply: true
