---
- name: Ensure working directory for Docker image build exists
  become: true
  ansible.builtin.file:
    path: "{{ spark_image_build_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure Docker image build files are synchronized
  become: true
  ansible.posix.synchronize:
    src: ./
    dest: "{{ spark_image_build_path }}/"
    archive: false
    recursive: true
    delete: true

- name: Ensure templated Docker image build files are present
  become: true
  ansible.builtin.template:
    src: "{{ spark_template }}"
    dest: "{{ spark_image_build_path }}/{{ spark_template | trim('.j2') }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - Dockerfile.j2
    - spark-defaults.conf.j2
  loop_control:
    loop_var: spark_template

- name: Build container image
  become: true
  community.docker.docker_image_build:
    name: spark-iceberg
    path: "{{ spark_image_build_path }}"
    rebuild: always

- name: Run container
  become: true
  community.docker.docker_container:
    name: spark
    image: spark-iceberg
    state: started
    detach: true
    restart: true
    restart_policy: unless-stopped
    recreate: true
    env:
      AWS_REGION: "{{ s3_region }}"
      AWS_ACCESS_KEY_ID: "{{ s3_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ s3_access_secret }}"
    published_ports:
      - "{{ spark_controller_ui_port }}:8080"
      - "{{ spark_connect_port }}:15002"
    volumes:
      - "{{ cephfs_mount_mount_path }}/staging/:/staging:ro"
