name: Run pytest
description: Run pytest using uv for dependencies management

inputs:
  pyproject-directory:
    description: Path to the directory containing pyproject.toml
    required: true
  pytest_file_or_dir:
    description: Path to a file or directory for pytest execution
    required: true
  uv-cache-dependency-glob:
    description: Cache dependencies based on the supplied glob
  uv-version:
    description: The version of uv to install e.g., `0.5.0` Defaults to the version in pyproject.toml or 'latest'.
    default: ""

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: ${{ inputs.uv-cache-dependency-glob }}
        version: ${{ inputs.uv-version }}

    - name: Install the project
      shell: bash -l {0}
      run: uv sync --locked --all-extras --dev
      working-directory: ${{ inputs.pyproject-directory }}

    - name: Run tests
      shell: bash -l {0}
      run: uv run pytest --durations-min=0.5 --exitfirst ${{ pytest_file_or_dir }} --cache-clear
      working-directory: ${{ inputs.pyproject-directory }}
