---
- name: Provision VMs for Iceberg's Nessie catalog
  hosts: localhost
  gather_facts: True
  vars:
    openstack_server_name: "nessie"
    openstack_flavor: l3.xsmall
    openstack_security_group_name: nessie
    openstack_security_group_description: Ingress to catalog ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ nessie_http_port }}"
        port_range_max: "{{ nessie_http_port }}"
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    inventory_group: nessie
  roles:
    - role: security_group_create
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: nessie
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
