[job]
name = "statusdisplay"
domain = "accelerator"
warehouse = "examples"

[[tables]]
name = "schedule"
write_mode = "replace"
partition = { "started_at" = "year" }
sort_order = { "cycle_name" = "asc" }

[transform]
dbt_dir = "warehouses/examples/transform"
dbt_select = "models/staging/sensor_data"
