---
- name: Provision VMs for the Lakekeeper catalog
  hosts: localhost
  gather_facts: True
  vars:
    openstack_server_name: lakekeeper
    openstack_flavor: l3.xsmall
    openstack_security_group_name: lakekeeper
    openstack_security_group_description: Ingress to catalog ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ lakekeeper_http_port }}"
        port_range_max: "{{ lakekeeper_http_port }}"
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    inventory_group: lakekeeper
  roles:
    - role: security_group_create
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: lakekeeper
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
