global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
  noColor: true

accessLog:
  addInternals: false
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  file:
    directory: /etc/traefik/dynamic
