global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  noColor: true

accessLog:
  addInternals: false
  filePath: /var/log/traefik/access.log

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
