global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR
  noColor: true

accessLog:
  addInternals: false
  filePath: /var/log/traefik/access.log

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  trinosecure:
    address: ":8443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
