---
lakekeeper_server_name: "{{ deploy_prefix }}lakekeeper"
lakekeeper_http_port: 8181
lakekeeper_base_path: /iceberg
lakekeeper_url: "https://{{ top_level_domain }}{{ lakekeeper_base_path }}"

lakekeeper_catalogs:
  - name: accelerator
    uri: "{{ lakekeeper_url }}/catalog"
    storage:
      bucket_name: isis-dataarchitecture-prototypes-warehouse-accelerator
      key_prefix: ""
  - name: management
    uri: "{{ lakekeeper_url }}/catalog"
    storage:
      bucket_name: isis-dataarchitecture-prototypes-warehouse-management
      key_prefix: ""
