---
- name: Configure Spark processing engine with Iceberg support
  hosts: spark
  roles:
   - name: cephfs_mount
   - name: geerlingguy.pip
     become: yes
   - name: geerlingguy.docker
     become: yes
   - name: spark
