# The following variables are required on the command line:
#  - openstack_cloud_name: Name of the cloud in ~/.config/clouds.yaml
#  - openstack_key_name: Name of the SSH key to add allowed to the deployed VM
#  - vm_config_file: Path to a yml file providing instance-specific VM variables.

- name: Read VM configuration
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: "../../group_vars/all/openstack.yml"
    - ansible.builtin.include_vars:
        file: "{{ vm_config_file }}"

- name: Provision VM for Apache Superset
  hosts: localhost
  gather_facts: false
  roles:
    - role: security_group_create
    - role: vm_create
