---
- name: Provision VMs for Trino service
  hosts: localhost
  gather_facts: False
  vars:
    openstack_security_group_name: trino
    openstack_security_group_description: Ingress to Trino ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ trino_http_port }}"
        port_range_max: "{{ trino_http_port }}"
    openstack_flavor: "{{ trino_vm_flavor }}"
    openstack_server_name: trino
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    inventory_group: trino
  roles:
    - role: security_group_create
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: trino
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
