---
- name: Create Keycloak working directory
  become: true
  ansible.builtin.file:
    path: "{{ keycloak_working_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Create certificates directory
  become: true
  ansible.builtin.file:
    path: "{{ keycloak_working_dir }}/certs"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Copy certificates
  become: true
  no_log: true
  ansible.builtin.copy:
    dest: "{{ keycloak_working_dir }}/certs/{{ certificate.filename }}"
    content: "{{ certificate.content }}"
    owner: root
    group: root
    mode: "u=r,o=r,g=r"
  loop:
    - { filename: stfc-ca.pem, content: "{{ stfc_ca_cert }}" }
  loop_control:
    loop_var: certificate

- name: Generate Dockerfile for optimized build
  become: true
  ansible.builtin.template:
    src: "{{ template_file.src }}"
    dest: "{{ keycloak_working_dir }}/{{ template_file.dest }}"
    mode: "{{ template_file.mode|default('u=rw,g=r,o=r') }}"
  loop:
    - { src: Dockerfile.j2, dest: Dockerfile }
  loop_control:
    loop_var: template_file

- name: Build optimized Keycloak image
  community.docker.docker_image_build:
    name: "{{ keycloak_image_optimized_name }}"
    path: "{{ keycloak_working_dir }}"
    rebuild: always

- name: Check if we need to bootstrap an admin
  no_log: "{{ not (keycloak_bootstrap_logging | default(false)) }}"
  ansible.builtin.uri:
    url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      client_id: "admin-cli"
      username: "{{ keycloak_local_admin.user }}"
      password: "{{ keycloak_local_admin.password }}"
      grant_type: "password"
  ignore_errors: true
  register: keycloak_token_response

- name: Set admin required fact
  ansible.builtin.set_fact:
    local_admin_user_exists: "{{ keycloak_token_response['status'] == 200 }}"

- name: Bootstrap Keycloak admin
  no_log: "{{ not (keycloak_bootstrap_logging | default(false)) }}"
  community.docker.docker_container:
    name: keycloak_bootstrap
    image: "{{ keycloak_image_optimized_name }}"
    command:
      [
        "bootstrap-admin",
        "user",
        "--password:env=KC_BOOTSTRAP_ADMIN_PASSWORD",
        "--optimized",
        "--no-prompt",
      ]
    state: started
    cleanup: true
    detach: false
    restart_policy: "no"
    recreate: true
    env:
      # comment to keep formatter moving this up one line
      KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ keycloak_bootstrap.admin_password }}"
      KC_DB_URL: "jdbc:postgresql://{{ keycloak_db_host }}:{{ keycloak_db_port }}/{{ keycloak_db_name }}"
      KC_DB_USERNAME: "{{ keycloak_db_user }}"
      KC_DB_PASSWORD: "{{ keycloak_db_password }}"
  when: not local_admin_user_exists

- name: Run Keycloak
  community.docker.docker_container:
    name: keycloak
    image: "{{ keycloak_image_optimized_name }}"
    command:
      [
        "start",
        "--optimized",
        "--http-enabled=true",
        "--hostname=https://{{ top_level_domain }}{{ keycloak_base_path }}",
        "--proxy-headers=xforwarded",
        "--proxy-trusted-addresses=127.0.0.0/8",
        "--log-level={{ keycloak_log_level }}",
      ]
    state: healthy
    cleanup: true
    detach: true
    restart_policy: unless-stopped
    recreate: true
    env:
      # comment to keep formatter moving this up one line
      KC_DB_URL: "jdbc:postgresql://{{ keycloak_db_host }}:{{ keycloak_db_port }}/{{ keycloak_db_name }}"
      KC_DB_USERNAME: "{{ keycloak_db_user }}"
      KC_DB_PASSWORD: "{{ keycloak_db_password }}"
    network_mode: host
    volumes:
      - "{{ keycloak_working_dir }}/certs/stfc-ca.pem:/opt/keycloak/conf/truststores/stfc-ca.pem:ro"
    comparisons:
      env: strict
    healthcheck:
      test: "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"
      interval: 5s
      timeout: 2s
      retries: 15

# Configure master realm admin
- name: Create permanent admin user
  no_log: true
  community.general.keycloak_user:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_bootstrap.admin_user }}"
    auth_password: "{{ keycloak_bootstrap.admin_password }}"
    realm: master
    username: "{{ keycloak_local_admin.user }}"
    enabled: true
    emailVerified: true
    credentials:
      - type: password
        value: "{{ keycloak_local_admin.password }}"
        temporary: false
    state: present
  register: kc_new_admin
  when: not local_admin_user_exists

- name: Assign admin realm role to permanent user
  no_log: "{{ not (keycloak_bootstrap_logging | default(false)) }}"
  community.general.keycloak_user_rolemapping:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_bootstrap.admin_user }}"
    auth_password: "{{ keycloak_bootstrap.admin_password }}"
    realm: master
    uid: "{{ kc_new_admin.end_state.id }}"
    roles:
      - name: "admin"
    state: present
  when: not local_admin_user_exists

- name: Disable temp-admin bootstrap account
  no_log: "{{ not (keycloak_bootstrap_logging | default(false)) }}"
  community.general.keycloak_user:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: "master"
    auth_username: "{{ keycloak_local_admin.user }}"
    auth_password: "{{ keycloak_local_admin.password }}"
    realm: master
    username: "{{ keycloak_bootstrap.admin_user }}"
    enabled: false
    state: present
  when: not local_admin_user_exists

# Configure custom realm
- ansible.builtin.import_tasks: setup-target-realm.yml
  vars:
    target_realm: "{{ keycloak_realm.name }}"
