[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[sources]
base_url = "http://172.16.103.105:8086"
channel_batch_size = 5

[load]
delete_completed_jobs = true
raise_on_max_retries = 1

# extract and normalize stages
[data_writer]
file_max_bytes = 10000000

[destination.filesystem]
layout = "{schema_name}/{table_name}/{YYYY}/{MM}/{DD}/{load_id}.{file_id}.{ext}"

[dev_influxdb.destination.filesystem]
bucket_url = './prod-warehouse-isis-staging/sources/'
auto_mkdir = true

[influxdb.destination.filesystem]
bucket_url = 's3://prod-warehouse-isis-staging/sources/'

[transform]
combined_machinestate_table = "accelerator.clean_machinestate"
