[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[sources]
base_url = "http://172.16.103.105:8086"
channel_batch_size = 5

[load]
delete_completed_jobs = true
raise_on_failed_jobs = false
raise_on_max_retries = 0

[elt_influxdb.destination.pyiceberg.catalog_properties]
name = "isis"
uri = "https://data-accelerator.isis.cclrc.ac.uk/nessie/iceberg/"

[dev_elt_influxdb.destination.pyiceberg.catalog_properties]
name = "isis"
uri = "sqlite:///iceberg-catalog.db"
warehouse = "./warehouse"
py-io-impl = "pyiceberg.io.pyarrow.PyArrowFileIO"
