- name: Dump current Openstack inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Gather server information from Openstack
      openstack.cloud.server_info:
        cloud: "{{ openstack_cloud_name }}"
      register: vms_info

    - name: Configure inventory groups
      ansible.builtin.blockinfile:
        path: "{{ inventory_filename }}"
        create: true
        block: |
          [{{ server.name | replace('-', '_') }}]
          {{ server.address }} ansible_user={{ openstack_vm_user }} ansible_python_interpreter=/usr/bin/python3
        append_newline: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ server.name }}"
        mode: "u=rw,g=r,o=r"
        state: present
      with_items: "{{ vms_info | community.general.json_query(addr_query) | rejectattr('address', 'none') }}"
      loop_control:
        loop_var: server
      vars:
        addr_query: "servers[*].{name: name, address: addresses.lakehouse[?starts_with(addr, '192.')].addr | [0]}"

    - name: Configure node options for SSH proxy
      ansible.builtin.blockinfile:
        path: "{{ inventory_filename }}"
        block: |
          [all:vars]
          ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q {{ openstack_vm_user }}@{{ openstack_management_vm_fip }}"'
        prepend_newline: true
        append_newline: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK [all:vars]"
        mode: "u=rw,g=r,o=r"
        state: present
