- name: Dump current Openstack inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Gather server information from Openstack
      openstack.cloud.server_info:
        cloud: "{{ openstack_cloud_name }}"
      register: vms_info

    - name: Configure inventory
      ansible.builtin.blockinfile:
        path: "{{ inventory_filename }}"
        create: true
        block: |
          [{{ item.name | replace('-', '_') }}]
          {{ item.addresses.Internal[0].addr }} ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
        append_newline: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
        mode: "u=rw,g=r,o=r"
        state: present
      with_items: "{{ vms_info['servers'] }}"
