---
- name: Provision VMs for Opralog opralogdb Server
  hosts: localhost
  vars:
    openstack_security_group_name: opralogdb
    openstack_security_group_description: Ingress to opralogdb ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ opralogdb_port }}"
        port_range_max: "{{ opralogdb_port }}"
    openstack_flavor: l3.tiny
    openstack_server_name: opralogdb
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    openstack_virtual_network:
      name: Internal
    inventory_group: opralogdb
  roles:
    - role: security_group_create
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: opralogdb
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
