# A development stack to emulate the Lakehouse. This is intended for local development only.
# See ./README.md

services:
  #########################################################
  # Ingress
  #
  # We make a certificate so that Traefik can be configured
  # with an enpoints with TLS-termination enabled.
  # This is primarily for Trino that requires the use of
  # HTTPS when authentication is enabled.
  #########################################################
  mkcert:
    container_name: local-lakehouse-mkcert
    image: alpine/mkcert
    entrypoint:
      - /bin/sh
      - -c
      - |
        certfile=/certs/localdev.pem
        if [ ! -f "$$certfile" ]; then
          echo "$$certfile not found. Creating new CA and certificate."
          cd /certs || exit 1
          mkcert -cert-file "$$certfile" -key-file localdev-key.pem localhost 127.0.0.1 ::1
          cp "$$(mkcert -CAROOT)"/* .
        else
          echo "$$certfile exists, skipping certificate creation."
        fi
    restart: "no"
    networks: &networks-common
      - local-lakehouse_net
    volumes:
      - "mkcert_data:/certs"

  adp-router:
    container_name: local-lakehouse-traefik
    image: traefik:v3.7.12
    env_file: &env_file-common
      - path: ./env-local
        required: true
    depends_on:
      mkcert:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - "50080:50080" # Web entry point
      - "59000:59000" # S3 entrypoint
      - "58443:8443" # TLS entrypoint for Trino (cannot run on non-root path prefix or without https with auth enabled)
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml"
      - "mkcert_data:/certs"
    networks: *networks-common

  #########################################################
  # Database shared by all services
  # Do not do this in production!
  #########################################################
  postgres-shared:
    container_name: local-lakehouse-postgres-shared
    image: postgres:18-bookworm
    env_file: *env_file-common
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -p 5432"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s
    networks: *networks-common
    volumes:
      - "postgres-shared_data:/var/lib/postgresql"

  postgres-shared-bootstrap:
    container_name: local-lakehouse-postgres-shared-bootstrap
    image: postgres:18-bookworm
    entrypoint:
      - /bin/bash
      - -c
      - |
        /postgres-ensuredb.sh postgres-shared $$POSTGRES_USER $$OPENFGA_DB_NAME
        /postgres-ensuredb.sh postgres-shared $$POSTGRES_USER $$LAKEKEEPER_DB_NAME
    env_file: *env_file-common
    restart: "no"
    depends_on:
      postgres-shared:
        condition: service_healthy
    networks: *networks-common
    volumes:
      - "./postgres-ensuredb.sh:/postgres-ensuredb.sh:ro"

  #########################################################
  # Keycloak identity provider
  #########################################################
  keycloak:
    container_name: local-lakehouse-keycloak
    image: &keycloak_image quay.io/keycloak/keycloak:26.3
    env_file: *env_file-common
    command:
      [
        "start-dev",
        "--metrics-enabled=true",
        "--health-enabled=true",
        "--features=token-exchange",
        "--hostname-debug=true",
        "--proxy-headers=xforwarded",
        "--verbose",
        "--log-level=INFO",
      ]
    volumes:
      - keycloak_data:/opt/keycloak/data
      - "./request-get.sh:/usr/local/bin/request-get.sh:ro"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "request-get.sh 8080 $$KC_HTTP_RELATIVE_PATH/realms/master/.well-known/openid-configuration jwks_uri",
        ]
      start_period: 20s
      start_interval: 5s
      interval: 15s
      timeout: 30s
      retries: 5
    networks: *networks-common

  keycloak-bootstrap:
    container_name: local-lakehouse-keycloak-bootstrap
    build:
      context: keycloak
      dockerfile: Dockerfile-kcadm.dockerfile
      args:
        base: *keycloak_image
    env_file: *env_file-common
    entrypoint:
      - /bin/sh
      - -c
      - "sleep 1; /opt/keycloak/bootstrap.sh http://keycloak:8080/auth"
    restart: "no"
    depends_on:
      keycloak:
        condition: service_healthy
    networks: *networks-common
    volumes:
      - "./keycloak/bootstrap.sh:/opt/keycloak/bootstrap.sh:ro"

  #########################################################
  # SeaweedFS - Object store emulating the Ceph object store.
  #########################################################
  seaweedfs:
    container_name: local-lakehouse-seaweedfs
    image: chrislusf/seaweedfs:4.45
    env_file: *env_file-common
    # Match ports on host & container to use the same port inside and outside the container
    # network
    command:
      - "mini"
      - "-dir=/data"
      - "-s3.iam.config=/etc/seaweedfs/iam.json"
      - "-s3.port=59000"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:59000/status || exit 1"]
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./seaweedfs/s3-iam-config.json:/etc/seaweedfs/iam.json:ro"
      - "seaweedfs_data:/data"
    networks: *networks-common

  #########################################################
  # OpenFGA - Permissioning
  #########################################################
  openfga-migrate:
    container_name: local-lakehouse-openfga-migrate
    image: &openfga-image openfga/openfga:v1.19.0
    env_file: *env_file-common
    command: migrate
    depends_on:
      postgres-shared-bootstrap:
        condition: service_completed_successfully
    networks: *networks-common

  openfga:
    container_name: local-lakehouse-openfga
    image: *openfga-image
    env_file: *env_file-common
    command: run
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    networks: *networks-common
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 10s
      timeout: 30s
      retries: 3

  #########################################################
  # Lakekeeper - Iceberg REST catalog
  #########################################################
  lakekeeper:
    container_name: local-lakehouse-lakekeeper
    image: &lakekeeper-image quay.io/lakekeeper/catalog:v0.13.3
    env_file: *env_file-common
    environment:
      #      - SSL_CERT_FILE=/certs/rootCA.pem
      - RUST_LOG=info,lakekeeper=${LAKEKEEPER_LOG_LEVEL:-info},lakekeeper_bin=${LAKEKEEPER_LOG_LEVEL:-info},iceberg_ext=${LAKEKEEPER_LOG_LEVEL:-info}
    command: ["serve"]
    healthcheck:
      test: ["CMD", "/home/nonroot/lakekeeper", "healthcheck"]
      start_period: 5s
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      lakekeeper-migrate:
        condition: service_completed_successfully
      adp-router:
        condition: service_healthy
      keycloak-bootstrap:
        condition: service_completed_successfully
      postgres-shared-bootstrap:
        condition: service_completed_successfully
    networks: *networks-common

  lakekeeper-migrate:
    container_name: local-lakehouse-lakekeeper-migrate
    image: *lakekeeper-image
    env_file: *env_file-common
    restart: "no"
    command: ["migrate"]
    depends_on:
      postgres-shared-bootstrap:
        condition: service_completed_successfully
      openfga:
        condition: service_healthy
    networks: *networks-common

  lakekeeper-bootstrap:
    container_name: local-lakehouse-lakekeeper-bootstrap
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    env_file: *env_file-common
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -euo pipefail
        for name in "$${WAREHOUSE_NAME}_landing" "$${WAREHOUSE_NAME}"; do \
          uv run /opt/work/bootstrap-warehouse.py \
            --lakekeeper-project-name "$$KC_REALM_NAME" \
            --keycloak-url "$$KEYCLOAK_URL_INTERNAL" \
            --keycloak-admin-credentials "$$KC_BOOTSTRAP_ADMIN_USERNAME:$$KC_BOOTSTRAP_ADMIN_PASSWORD" \
            --keycloak-user-realm "$$KC_REALM_NAME" \
            --bootstrap-credentials "machine-infra:s3cr3t" \
            --token-scope lakekeeper \
            --server-admin "$$ADMIN_USER" \
            --log-level=DEBUG \
            --warehouse-json-file "/opt/work/warehouses/$$name.json" \
            "http://lakekeeper:8181"; \
        done
    restart: "no"
    depends_on:
      lakekeeper:
        condition: service_healthy
    volumes:
      - "../ansible/roles/lakekeeper/files/bootstrap-warehouse.py:/opt/work/bootstrap-warehouse.py"
      - "./warehouses/lakekeeper:/opt/work/warehouses:ro"
    networks: *networks-common

# #########################################################
# # Marimo notebooks
# #########################################################
# marimo:
#   container_name: local-lakehouse-marimo
#   build:
#     context: marimo
#   env_file: *env_file-common
#   healthcheck:
#     test: ["CMD-SHELL", "request-get.sh 8080 /health healthy"]
#     start_period: 5s
#     interval: 30s
#     timeout: 30s
#   networks: *networks-common
#   volumes:
#     - ./marimo/notebooks:/home/nbuser/notebooks
#     - "./request-get.sh:/usr/local/bin/request-get.sh:ro"
# #########################################################
# # Trino query engine
# #########################################################

# trino:
#   container_name: local-lakehouse-trino
#   image: trinodb/trino:477
#   env_file: *env_file-common
#   depends_on:
#     keycloak:
#       condition: service_healthy
#     adp-router:
#       condition: service_healthy
#   healthcheck:
#     test: ["CMD", "curl", "-I", "http://localhost:8080/v1/status"]
#     start_period: 10s
#     interval: 30s
#     timeout: 30s
#     retries: 2
#   volumes:
#     - "./trino/etc:/etc/trino"
#     - "./warehouses/trino:/etc/trino/catalog"
#   networks: *networks-common

# #########################################################
# # Shared Redis cache for Superset and Airflow
# #########################################################
# shared-redis:
#   container_name: local-lakehouse-shared-redis
#   env_file: *env_file-common
#   image: redis:8.4-bookworm
#   healthcheck:
#     test: ["CMD", "redis-cli", "ping"]
#     interval: 30s
#     timeout: 30s
#     retries: 50
#     start_period: 30s
#   restart: unless-stopped
#   volumes:
#     - shared_redis_data:/data
#   networks: *networks-common

networks:
  local-lakehouse_net:
    name: local-lakehouse-network

volumes:
  mkcert_data:
    name: local-lakehouse_mkcert_data
  postgres-shared_data:
    name: local-lakehouse_postgres-shared_data
  keycloak_data:
    name: local-lakehouse_keycloak_data
  seaweedfs_data:
    name: local-lakehouse_seaweedfs_data


  # marimo_data:
  #   name: local-lakehouse_marimo_data
  # shared_redis_data:
  #   name: local-lakehouse_shared_redis_data
  # uv_cache:
  #   name: local-lakehouse_uv_cache
