# Superset instance: facility_ops
include:
  - ./docker-compose.yml

x-base-file: &base-file docker-compose-superset.base.yml

x-environment: &environ
  SUPERSET_APP_ROOT: /workspace/facility_ops
  SUPERSET_CONFIG_PATH: /app/docker/pythonpath/superset_config_fops.py
  SUPERSET_REDIS_DB: 1
  WAREHOUSE: facility_ops

services:
  superset-fops-bootstrap:
    container_name: local-lakehouse-superset-fops-bootstrap
    extends:
      file: *base-file
      service: superset-bootstrap
    environment: *environ

  superset-fops-app:
    container_name: local-lakehouse-superset-fops-app
    extends:
      file: *base-file
      service: superset-app
    environment: *environ
    depends_on:
      superset-fops-bootstrap:
        condition: service_completed_successfully

  superset-facility_ops-worker:
    container_name: local-lakehouse-superset-fops-worker
    extends:
      file: *base-file
      service: superset-worker
    depends_on:
      superset-fops-app:
        condition: service_healthy

  superset-facility_ops-worker-beat:
    container_name: local-lakehouse-superset-fops-worker-beat
    extends:
      file: *base-file
      service: superset-worker-beat
    depends_on:
      superset-fops-app:
        condition: service_healthy
