---
- name: Ensure postgres data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ postgres_db_data_path }}"
    state: directory
    mode: '0755'

- name: Ensure secrets directory exists
  become: true
  ansible.builtin.file:
    path: /secrets
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure postgres secrets are available
  become: yes
  ansible.builtin.copy:
    dest: /secrets/postgres-passwd
    content: "{{ postgres_db_passwd }}"
    owner: root
    group: root
    mode: "u=r,g=r,o=r"

- name: Ensure Postgresql container is running
  become: true
  community.docker.docker_container:
    name: postgres
    image: "{{ postgres_image }}"
    state: started
    cleanup: true
    detach: true
    restart: true
    published_ports:
      - "{{ postgres_db_port }}:5432"
    env:
      POSTGRES_DB="{{ postgres_db_name }}"
      POSTGRES_USER="{{ postgres_db_user }}"
      POSTGRES_PASSWORD_FILE=/secrets/postgres-passwd
    volumes:
      - "{{ postgres_db_data_path }}:/data"
      - /secrets:/secrets:ro
