---
- name: Provision VMs for Trino service
  hosts: localhost
  vars:
    openstack_security_group_name: trino
    openstack_security_group_description: Ingress to Trino ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ trino_http_port }}"
        port_range_max: "{{ trino_http_port }}"
    openstack_flavor: l3.nano
    openstack_server_name: trino
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    openstack_vm_user: ubuntu
    inventory_group: trino
  roles:
    - role: security_group_create
    - role: vm_create
