---
- name: Configure Metabase
  hosts: metabase
  roles:
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker
      become: true
    - role: postgres
    - role: metabase
