---
- name: Ensure /etc/hosts is updated
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ groups[inventory_group][0] }}    {{ inventory_group }}
    prepend_newline: true
    append_newline: true
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ inventory_group }}"
    mode: "u=rw,g=r,o=r"
