docs_dir: src
site_name: ISIS Accelerator Data Platform - Developer
site_url: https://data-accelerator.isis.cclrc.ac.uk/docs-devel/
site_author: ISIS Computing Division
site_description: Developer documentation for the ISIS Data Platform Prototype
theme:
  name: readthedocs
  logo: assets/images/logo.svg
plugins:
  - autorefs
  - search
markdown_extensions:
  - admonition
  - tables
