---
- name: Provision VMs for Keycloak server
  hosts: localhost
  gather_facts: True
  vars:
    openstack_server_name: "keycloak"
    openstack_flavor: l3.micro
    openstack_security_group_name: keycloak
    openstack_security_group_description: Ingress to keycloak ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ keycloak_http_port }}"
        port_range_max: "{{ keycloak_http_port }}"
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ keycloak_http_management_port }}"
        port_range_max: "{{ keycloak_http_management_port }}"
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    inventory_group: keycloak
  roles:
    - role: security_group_create
    - role: vm_create
