---
- name: Configure jaeger prerequisites
  hosts: jaeger
  roles:
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker
      become: true
    - role: jaeger
