---
- name: Configure Postgres DB to act as an Iceberg catalog
  hosts: iceberg_catalog
  roles:
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker
      become: true
    - role: postgres
