---
- name: Configure Jupyter Notebook instance
  hosts: jupyter
  roles:
    - role: cephfs_mount
    - role: geerlingguy.pip
      become: true
    - role: geerlingguy.docker
      become: true
    - role: jupyter
