- name: List docker images
  hosts: all:!elt
  tasks:
    - name: List docker images
      ansible.builtin.command: docker image ls
      register: docker_images
      changed_when: false
      failed_when: docker_images.rc != 0

    - name: Print image list
      ansible.builtin.debug:
        msg: "{{ docker_images.stdout_lines }}"
