[job]
name = "opralogweb"
domain = "accelerator"
warehouse = "examples"
extract = "elt_common.sources.sqldatabase:DatabaseExtract"

[[tables]]
name = "Logbooks"
write_mode = "append"
cursor_column = "LogbookId"

[[tables]]
name = "Entries"
write_mode = "append"
cursor_column = "EntryId"
partition = { "EntryId" = "bucket[4]" }
sort_order = { "EntryId" = "asc" }

[transform]
dbt_dir = "warehouses/examples/transform"
dbt_select = "models/staging/sensor_data"
