---
- name: Provision VMs for minio service
  hosts: localhost
  gather_facts: False
  vars:
    openstack_security_group_name: minio
    openstack_security_group_description: Ingress to minio ports
    openstack_security_group_rules:
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ minio_rest_port }}"
        port_range_max: "{{ minio_rest_port }}"
      - direction: ingress
        ether_type: IPv4
        protocol: tcp
        port_range_min: "{{ minio_console_port }}"
        port_range_max: "{{ minio_console_port }}"
    openstack_flavor: l3.nano
    openstack_server_name: minio
    openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
    inventory_group: minio
  roles:
    - role: security_group_create
    - role: vm_create
