---
- import_playbook: site_ssh_auth_users.yml
- import_playbook: site_traefik.yml
- import_playbook: site_datastore.yml
- import_playbook: site_keycloak.yml
- import_playbook: site_lakekeeper.yml
- import_playbook: site_trino.yml
- import_playbook: site_superset_farm.yml
- import_playbook: site_elt.yml
