---
# VM config
openstack_server_name: elt
openstack_flavor: l3.xsmall
openstack_security_groups: [default]

# Deployment config
elt_uv_python_version: "3.13"
elt_git_clone_dir: "{{ ansible_env['HOME'] }}/var/git"
elt_cron_root_dir: "{{ ansible_env['HOME'] }}/var/cron"
elt_cron_logs_root_dir: "{{ ansible_env['HOME'] }}/var/cron/logs"
elt_secrets_root_dir: /secrets/warehouses

elt_warehouses:
  - name: accelerator
    github_org: ISISNeutronMuon
    github_repo: analytics-data-platform
    sub_dir: warehouses/accelerator
    sources:
      - name: statusdisplay
        hour: 0
        minute: 15
        dbt_args: "--select 'staging/statusdisplay+'"
elt_threads: 16

logrotate_frequency: weekly
logrotate_keep: 30
logrotate_compress: true
