[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[sources]
base_url = "https://status.isis.stfc.ac.uk/api"
resources = ["schedule"]

[elt_statusdisplay.destination.pyiceberg.catalog_properties]
name = "isis"
uri = "https://data-accelerator.isis.cclrc.ac.uk/nessie/iceberg/"

[dev_elt_statusdisplay.destination.pyiceberg.catalog_properties]
name = "isis"
uri = "sqlite:///:memory:"
warehouse = "./warehouse"
py-io-impl = "pyiceberg.io.pyarrow.PyArrowFileIO"
