[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[sources]
base_url = "https://status.isis.stfc.ac.uk/api"
resources = ["schedule"]

[destination]
catalog_name = "isis"
catalog_uri = "https://data-accelerator.isis.cclrc.ac.uk/nessie/iceberg/"
