---
postgres_db:
  user: "{{ vault_self_hosted_db['user'] }}"
  password: "{{ vault_self_hosted_db['password'] }}"
  databases:
    - { name: keycloak, password: "{{ secrets_keycloak['db_name'] }}" }
    # - openfga
    # - lakekeeper
    # - superset_farm

minio_root_user: "{{ vault_minio['user'] }}"
minio_root_password: "{{ vault_minio['password'] }}"
