---
keycloak_db_dbname: keycloak
keycloak_db_host: "{{ groups['datastore'][0] }}"
keycloak_db_port: 5432
keycloak_db_user: "{{ vault_shared_db['user'] }}"
keycloak_db_passwd: "{{ vault_shared_db['password'] }}"
