---
# The following variables are required on the command line:
#  - deploy_type: One of {qa}
#  - openstack_cloud_name: Name of the cloud in ~/.config/clouds.yaml
#  - openstack_key_name: Name of the SSH key to add allowed to the deployed VM
#  - openstack_server_name: Name of the deployed VM. A file is expected in
#                           '../../group_vars/{{ deploy_type }}/{{ openstack_server_name }}.yml'
#                            to provide the openstack variables to configure the machine.

- name: Read VM configuration for configuring Apache Superset
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: "../../group_vars/{{ deploy_type }}/openstack.yml"
    - ansible.builtin.include_vars:
        file: "../../group_vars/{{ deploy_type }}/{{ openstack_server_name }}.yml"

- name: Provision VMs for Apache Superset
  hosts: localhost
  gather_facts: false
  roles:
    - role: security_group_create
    - role: vm_create
