---
# Specialized variables for the Superset VM. See ../../vars/openstack.yml for shared values

# We run multiple instances of Apache Superset on a single node to maximise resource usage.
openstack_server_name: superset_farm
openstack_security_group_name: superset
openstack_security_group_description: Ingress to superset ports
openstack_security_group_rules:
  - direction: ingress
    ether_type: IPv4
    protocol: tcp
    port_range_min: 8088 # how can we not duplicate this...
    port_range_max: 8089
openstack_flavor: l3.xsmall
openstack_security_groups: [default, "{{ openstack_security_group_name }}"]
