---
- name: Ensure Jupyter notebook directory exists
  become: true
  ansible.builtin.file:
    path: "{{ jupyter_notebook_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure working directory for Docker image build exists
  become: yes
  ansible.builtin.file:
    path: "{{ jupyter_image_build_path }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure Docker image build files are synchronized
  become: yes
  ansible.posix.synchronize:
    src: ./
    dest: "{{ jupyter_image_build_path }}/"
    recursive: yes
    delete: yes

- name: Build container image
  become: yes
  community.docker.docker_image_build:
    name: jupyter-pyspark
    path: "{{ jupyter_image_build_path }}"
    rebuild: always

- name: Run container
  become: yes
  community.docker.docker_container:
    name: jupyter
    image: jupyter-pyspark
    state: started
    cleanup: true
    detach: true
    env:
      SPARK_REMOTE: "{{ spark_connect_endpoint }}"
    restart-policy: always
    published_ports:
      - "{{ jupyter_notebook_port }}:8888"
    volumes:
      - "{{ jupyter_notebook_path }}:/var/lib/jupyter/notebooks"
