[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[sources]
base_url = "https://status.isis.stfc.ac.uk/api"
resources = ["schedule"]

[sources.data_writer]
file_max_items = 100000

[normalize]
workers = 3

[load]
delete_completed_jobs = true
raise_on_max_retries = 1
workers = 5

[destination.filesystem]
layout = "{table_name}/{YYYY}/{MM}/{DD}/{load_id}.{file_id}.{ext}"
