---
- name: Provision management VM
  hosts: localhost
  gather_facts: False
  vars:
    openstack_flavor: l3.nano
    openstack_server_name: management_vm
    openstack_security_groups: [default]
    openstack_server_fip: "{{ openstack_management_vm_fip }}"
    inventory_group: management_vm
  roles:
    - role: vm_create
