---
- name: Ensure Python openstack bindings are present
  ansible.builtin.pip:
   name: "python-openstackclient=={{ openstackclient_version }}"
   state: present

- name: Ensure cloud server is present
  openstack.cloud.server:
    cloud: "{{ openstack_cloud_name }}"
    flavor: "{{ openstack_flavor }}"
    image: "{{ openstack_image }}"
    name: "{{ openstack_server_name }}"
    key_name: "{{ openstack_key_name }}"
    network: Internal
    auto_floating_ip: no
    security_groups: [default, "{{ openstack_security_group_name }}"]
    timeout: 200
    state: present
  register: vm_info

- name: Set IP address fact
  ansible.builtin.set_fact:
    _runner_ip: "{{ vm_info.server.addresses.Internal[0].addr }}"

- name: Get IP address of VM
  ansible.builtin.debug:
    msg: "{{ _runner_ip }}"

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 300
  delegate_to: "{{ _runner_ip }}"

- name: Ensure instance is associated with a group
  ansible.builtin.add_host:
    name: "{{ _runner_ip }}"
    groups: "{{ inventory_group }}"
    ansible_user: "{{  openstack_vm_user }}"
