---
- include_tasks: ../../../tasks/ensure_openstack_bindings.yml

- name: Ensure cloud server is present
  openstack.cloud.server:
    cloud: "{{ openstack_cloud_name }}"
    flavor: "{{ openstack_flavor }}"
    image: "{{ openstack_image }}"
    name: "{{ openstack_server_name }}"
    key_name: "{{ openstack_key_name }}"
    network: "{{ openstack_virtual_network.name | default('Internal') }}"
    auto_floating_ip: false
    security_groups: "{{ openstack_security_groups }}"
    timeout: 200
    state: present
  register: vm_info

- name: Associate floating IP to instance
  openstack.cloud.floating_ip:
    cloud: "{{ openstack_cloud_name }}"
    server: "{{ openstack_server_name }}"
    network: "{{ openstack_virtual_network.name }}"
    floating_ip_address: "{{ openstack_server_fip }}"
  when: openstack_server_fip is defined

- name: Set fact for IP address of VM (Internal network)
  ansible.builtin.set_fact:
    vm_ip_address: "{{ vm_info.server.addresses[openstack_virtual_network.name][0].addr }}"
    cacheable: false
  when: openstack_server_fip is not defined

- name: Set fact for IP address of VM (Private network)
  ansible.builtin.set_fact:
    vm_ip_address: "{{ openstack_server_fip }}"
    cacheable: false
  when: openstack_server_fip is defined

- name: Display IP address of VM
  ansible.builtin.debug:
    msg: "{{ openstack_server_name }}: {{ vm_ip_address }}"

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 300
  delegate_to: "{{ vm_ip_address }}"
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ openstack_vm_user }}@{{ openstack_jump_host }}"'

- name: Ensure instance is associated with a group
  ansible.builtin.add_host:
    name: "{{ vm_ip_address }}"
    groups: "{{ inventory_group }}"
    ansible_user: "{{ openstack_vm_user }}"
    ansible_python_interpreter: "{{ openstack_python_interpreter }}"

- name: Ensuring machine is up to date
  include_role:
    name: packages_update
    apply:
      delegate_to: "{{ vm_ip_address }}"
  when: vm_create_package_update
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ openstack_vm_user }}@{{ openstack_jump_host }}"'
