---
- include_tasks: ../../../tasks/ensure_openstack_bindings.xml

- name: Ensure cloud server is present
  openstack.cloud.server:
    cloud: "{{ openstack_cloud_name }}"
    flavor: "{{ openstack_flavor }}"
    image: "{{ openstack_image }}"
    name: "{{ openstack_server_name }}"
    key_name: "{{ openstack_key_name }}"
    network: Internal
    auto_floating_ip: false
    security_groups: "{{ openstack_security_groups }}"
    timeout: 200
    state: present
  register: vm_info

- name: Get IP address of VM
  ansible.builtin.debug:
    msg: "{{ openstack_server_name }}: {{ vm_info.server.addresses.Internal[0].addr }}"

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 300
  delegate_to: "{{ vm_info.server.addresses.Internal[0].addr }}"

- name: Ensure instance is associated with a group
  ansible.builtin.add_host:
    name: "{{ vm_info.server.addresses.Internal[0].addr }}"
    groups: "{{ inventory_group }}"
    ansible_user: "{{ openstack_vm_user }}"
    ansible_python_interpreter: "{{ openstack_python_interpreter }}"

- name: Ensuring machine is up to date
  include_role:
    name: packages_update
    apply:
      delegate_to: "{{ vm_info.server.addresses.Internal[0].addr }}"
  when: vm_create_package_update
