---
secrets_self_hosted_db: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/self_hosted_db')['data']['data'] }}"
secrets_minio: "{{ lookup('community.hashi_vault.vault_read', secrets_prefix_env + '/minio-creds')['data']['data'] }}"
