---
- name: Ensure cron scripts directory exists
  ansible.builtin.file:
    path: "{{ ingestion_elt_cron_scripts_dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Create/update ELT cron script template
  ansible.builtin.template:
    src: ./cron/elt_task.sh.j2
    dest: "{{ ingestion_elt_cron_scripts_dir }}/elt_task.sh"
    mode: "u=rwx,g=rx,o=rx"

# ---------- statusdisplay ----------
- name: Ensure statusdisplay cron logs directory exists
  become: true
  ansible.builtin.file:
    path: "{{ ingestion_elt_cron_log_dir }}/statusdisplay"
    state: directory
    recurse: true
    mode: "u=rwx,g=rx,o=rx"
    owner: 1000
    group: 1000

- name: Ensure daily statusdisplay ingest job exists
  ansible.builtin.cron:
    name: "Statusdisplay ingest"
    minute: "15"
    hour: "0"
    job: "{{ ingestion_elt_cron_scripts_dir }}/elt_task.sh pipelines/ingest/statusdisplay pipelines/modelling/isis --select '+models/facility' > {{ ingestion_elt_cron_log_dir }}/statusdisplay/elt-$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).log 2>&1"

# ---------- Opralog ----------
- name: Ensure Opralog cron logs directory exists
  become: true
  ansible.builtin.file:
    path: "{{ ingestion_elt_cron_log_dir }}/opralogweb"
    state: directory
    recurse: true
    mode: "u=rwx,g=rx,o=rx"
    owner: 1000
    group: 1000

- name: Ensure daily Opralog ingest job exists
  ansible.builtin.cron:
    name: "Opralog ingest"
    state: "present"
    minute: "10"
    hour: "2"
    job: "{{ ingestion_elt_cron_scripts_dir }}/elt_task.sh pipelines/ingest/opralogweb pipelines/modelling/isis --select '+models/accelerator' > {{ ingestion_elt_cron_log_dir }}/opralogweb/elt-$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).log 2>&1"
