---
- name: Provision VM for data ingestion
  hosts: localhost
  vars:
    openstack_flavor: l3.xsmall
    openstack_server_name: "ingestion"
    openstack_security_groups: [default]
    inventory_group: ingestion
  roles:
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: ingestion
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
