---
- name: Provision VM for data ingestion
  hosts: localhost
  vars:
    openstack_flavor: l3.xsmall
    openstack_server_name: "ingestion"
    openstack_security_groups: [default]
    inventory_group: ingestion
  roles:
    - role: vm_create
