---
# Implicit localhost is not included in all so doesn't load the all variables by default
- name: Include all group variables (for localhost)
  hosts: localhost
  tasks:
    - ansible.builtin.include_vars:
        dir: group_vars/all

# Openstack resources
- import_playbook: playbooks/minio/create.yml
- import_playbook: playbooks/iceberg_catalog/create.yml
- import_playbook: playbooks/spark/create.yml
- import_playbook: playbooks/jupyter/create.yml
- import_playbook: playbooks/trino/create.yml

- name: Include all group variables (for all hosts)
  hosts: all
  tasks:
    - ansible.builtin.include_vars:
        dir: group_vars/all

# Dump information on new hosts.
- import_playbook: playbooks/inventory/inventory_persist.yml

# System tasks
- import_playbook: playbooks/system/update.yml

# Services
- import_playbook: playbooks/minio/setup.yml
- import_playbook: playbooks/iceberg_catalog/setup.yml
- import_playbook: playbooks/spark/setup.yml
- import_playbook: playbooks/jupyter/setup.yml
- import_playbook: playbooks/trino/setup.yml
