---
# Implicit localhost is not included in all so doesn't load the all variables by default
- name: Include all group variables
  hosts: localhost
  tasks:
    - ansible.builtin.include_vars:
        dir: group_vars/all

# Openstack resources
- import_playbook: playbooks/minio/start.yml
- import_playbook: playbooks/iceberg_catalog/start.yml
- import_playbook: playbooks/spark/start.yml
- import_playbook: playbooks/jupyter/start.yml
- import_playbook: playbooks/trino/start.yml

# Dump inventory
- import_playbook: playbooks/inventory/persist.yml

- name: Include all group variables
  hosts: all
  tasks:
    - ansible.builtin.include_vars:
        dir: group_vars/all

# Apply updates
- import_playbook: playbooks/system/update.yml

# Services
- import_playbook: playbooks/minio/setup.yml
- import_playbook: playbooks/iceberg_catalog/setup.yml
- import_playbook: playbooks/spark/setup.yml
- import_playbook: playbooks/jupyter/setup.yml
- import_playbook: playbooks/trino/setup.yml
