---
- name: Provision VMs for JupyterHub
  hosts: localhost
  vars:
    openstack_flavor: l6.c32
    openstack_server_name: "jupyterhub"
    openstack_security_groups: [default, "HTTP"]
    inventory_group: jupyterhub
  roles:
    - role: vm_create
