---
- name: Provision VMs for JupyterHub
  hosts: localhost
  vars:
    openstack_flavor: l6.c32
    openstack_server_name: "jupyterhub"
    openstack_security_groups: [default, "HTTP"]
    inventory_group: jupyterhub
  roles:
    - role: vm_create

- import_playbook: ../inventory/inventory_persist.yml

- name: (Re-)configure /etc/hosts across all nodes
  hosts: all:!localhost
  gather_facts: True
  vars:
    inventory_group: jupyterhub
  tasks:
    - ansible.builtin.include_tasks: ../../tasks/configure_etc_hosts.yml
