---
postgres_db_data_path: "{{ cephfs_mount_mount_path }}/live/nessie/data"
postgres_container_network: "{{ nessie_container_network }}"
postgres_port: "{{ nessie_store_port }}"
postgres_db_user: "{{ nessie_store_user }}"
postgres_db_passwd: "{{ nessie_store_passwd }}"
postgres_db_names:
  # Catalog backend
  - "{{ nessie_store_dbname }}"
  # Nessie management database. See https://projectnessie.org/guides/management/
  - "{{ nessie_store_dbname }}_gc"
