---
# WARNING: This needs to match the version running in the Spark Dockerfile
- name: Install required APT packages
  become: true
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jdk
      - python3
      - python3-dev
    state: present

# TLJH with the first-time authenticator creates new users and home directories
# for each new user. If our home directories persist on a shared volume the
# uid/gid of each home directory keeps their original value. TLJH offers no
# control over uid/gid assignment for the new users and this may end up differing
# from the persistent home directories. We set a uid_min/gid_min to a high range
# to avoid conflicts with any users the cloud setup creates and create new users
# with matching uid/gid values to the existing directories

- name: Ensure new TLJH users get uids that won't conflict with existing users on a new machine
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^UID_MIN\\s+"
    line: "UID_MIN\t10000"

- name: Ensure new TLJH users get gids that won't conflict with existing users on a new machine
  become: true
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^GID_MIN\\s+"
    line: "GID_MIN\t10000"

- name: Ensure persistent home directory root exists
  become: true
  ansible.builtin.file:
    path: "{{ jupyterhub_home_root_path }}"
    state: directory
    mode: "0755"

- name: Change default directory for home directories
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: "^HOME="
    line: "HOME={{ jupyterhub_home_root_path }}"

- name: Ensure skeleton ipython directory exists
  become: true
  ansible.builtin.file:
    path: "/etc/skel/.ipython"
    state: directory
    mode: "0755"

- name: Add additional skeleton content for each new user created
  become: true
  ansible.posix.synchronize:
    use_ssh_args: true
    src: ipython/
    dest: /etc/skel/.ipython/
    archive: false
    recursive: true
    delete: true

- name: Check for any existing Jupyterhub user home directories
  ansible.builtin.find:
    paths: "{{ jupyterhub_home_root_path }}"
    patterns: "jupyter-*"
    recurse: no
    file_type: directory
  register: jupyter_user_home_dirs

- name: Create any users that don't yet exist on the system but have home directories
  become: true
  ansible.builtin.user:
    name: "{{ jupyter_user_home_dir.path.split('/')[-1] }}"
    create_home: false
  loop: "{{ jupyter_user_home_dirs['files'] }}"
  loop_control:
    loop_var: jupyter_user_home_dir

- name: Download The Littlest JupyterHub bootstrap script
  ansible.builtin.get_url:
    url: https://github.com/jupyterhub/the-littlest-jupyterhub/raw/refs/tags/2.0.0/bootstrap/bootstrap.py
    dest: /tmp/bootstrap.py
    mode: "u=rwx,g=rx,o=rx"

# Start the default server once to create the directory structure
# We'll then copy our configuration over and reload
- name: Run bootstrap script
  become: true
  ansible.builtin.command:
    cmd: python3 /tmp/bootstrap.py
    creates: /opt/tljh/installer.log

- name: Copy user-requirements template
  become: true
  vars:
    user_req_dest:
  ansible.builtin.copy:
    src: user-requirements.in
    dest: /opt/tljh/tljh-user-requirements.in
    mode: u=rw,g=rw,o=r

- name: Install pip tools
  become: true
  ansible.builtin.pip:
    executable: /opt/tljh/user/bin/pip
    name:
      - pip-tools==7.4.1

- name: Generate user-requirements.txt
  become: true
  ansible.builtin.command:
    cmd: |-
      /opt/tljh/user/bin/pip-compile
        --quiet --strip-extras --no-annotate -o tljh-user-requirements.txt tljh-user-requirements.in
    chdir: /opt/tljh
    creates: /opt/tljh/tljh-user-requirements.txt

- name: Install user-requirements.txt
  become: true
  ansible.builtin.pip:
    executable: /opt/tljh/user/bin/pip
    requirements: /opt/tljh/tljh-user-requirements.txt

- name: Query location of PySpark root (SPARK_HOME)
  become: true
  ansible.builtin.command:
    cmd: /opt/tljh/user/bin/python -c "import pyspark;print(pyspark.__path__[0])"
  register: pyspark_root

- name: Ensure PySpark root conf path exists
  become: true
  ansible.builtin.file:
    path: "{{ pyspark_root.stdout }}/conf"
    state: directory
    mode: "0755"

- name: Ensure Spark config files are present
  become: true
  ansible.builtin.template:
    src: spark/spark-defaults.conf.j2
    dest: "{{ pyspark_root.stdout }}/conf/spark-defaults.conf"
    mode: "u=rw,g=r,o=r"

- name: Ensure JupyterHub config files are present and up to date
  become: true
  ansible.builtin.template:
    src: "{{ jupyterhub_template }}"
    dest: "/opt/tljh/{{ jupyterhub_template | replace('.j2', '') }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - config/config.yaml.j2
    - config/jupyterhub_config.d/00-spawner.py.j2
    - config/jupyterhub_config.d/01-jupyterhub.py.j2
  loop_control:
    loop_var: jupyterhub_template
  register: jupyterhub_configs

- name: Ensure Jupyter config files are present
  become: true
  ansible.posix.synchronize:
    use_ssh_args: true
    src: jupyter/
    dest: /opt/tljh/notebook/
    archive: false
    recursive: true
    delete: true

- name: Reload JupyterHub
  become: true
  ansible.builtin.command:
    cmd: tljh-config reload hub
  when: jupyterhub_configs.changed
