name: tram_ops
version: "1.0.0"

# default project points at stack in local/infra
profile: "infra-local"

flags:
  require_certificate_validation: True

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dispatch: # Use macros from trino_utils in preference. https://hub.getdbt.com/starburstdata/trino_utils/latest/
  - macro_namespace: dbt_utils
    search_order: ['trino_utils', 'dbt_utils']
  - macro_namespace: dbt_date
    search_order: ['trino_utils', 'dbt_date']
  - macro_namespace: metrics
    search_order: ['trino_utils', 'metrics']


models:
  +file_format: parquet
  +materialized: view
  tram_ops:
    # The full schema name of the final tables is "{target_schema}_"{custom_schema}"
    #   - 'target_schema' is defined in profiles.yml
    #   - 'custom_schema' is defined for each collection of models below
    # See https://docs.getdbt.com/docs/build/custom-schemas
    staging:
      +schema: staging
    marts:
      +schema: marts
      +materialized: table
