docs_dir: src
site_name: ISIS Accelerator Data Platform
site_url: https://data-accelerator.isis.cclrc.ac.uk/
site_author: ISIS Computing Division
site_description: Documentation for the ISIS Accelerator Data Platform
theme:
  name: material
  logo: assets/images/logo.svg
extra_css:
  - stylesheets/extra.css
plugins:
  - autorefs
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
