---
- name: Install Python psycopg2 package
  ansible.builtin.include_role:
    name: geerlingguy.pip
    apply:
      become: true
      vars:
        pip_install_packages:
          - name: psycopg2-binary
            version: ">=2.5.1"
            extra_args: --break-system-packages

- name: Ensure postgres data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ postgres_db_data_path }}"
    state: directory
    owner: 999
    group: 999
    mode: "u=rwx,g=,o="

- name: Create secrets directory exists
  become: true
  ansible.builtin.file:
    path: /secrets
    state: directory
    owner: 999
    group: 999
    mode: "u=rwx,g=,o="

- name: Create postgres secrets
  become: true
  ansible.builtin.copy:
    dest: /secrets/postgres-passwd
    content: "{{ postgres_db_password }}"
    owner: root
    group: root
    mode: "u=r,g=r,o=r"

- name: Run Postgresql
  become: true
  community.docker.docker_container:
    name: postgres
    image: "{{ postgres_image }}"
    state: healthy
    cleanup: true
    detach: true
    network_mode: host
    restart_policy: unless-stopped
    env:
      #
      POSTGRES_USER="{{ postgres_db_user }}"
      POSTGRES_PASSWORD_FILE=/secrets/postgres-passwd
    volumes:
      - "{{ postgres_db_data_path }}:/var/lib/postgresql"
      - /secrets:/secrets:ro

- name: Create required users
  become: true
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_host: localhost
    login_user: "{{ postgres_db_user }}"
    login_password: "{{ item.password }}"
  loop: "{{ postgres_db_databases }}"
  loop_control:
    label: "{{ item.name }}"
  retries: 5
  delay: 2

- name: Create required databases
  become: true
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.name }}"
    login_host: localhost
    login_user: "{{ postgres_db_user }}"
    login_password: "{{ postgres_db_password }}"
  loop: "{{ postgres_db_databases }}"
  loop_control:
    label: "{{ item.name }}"
  retries: 5
  delay: 2
