---
- ansible.builtin.include_tasks: ../../../tasks/ensure_openstack_apt_keys.yml

- name: Ensure all packages are up to date
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: "yes"
  retries: 3
  delay: 5
  register: updates
  until: not updates.failed

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Ensure system is rebooted (if required)
  become: true
  ansible.builtin.reboot:
    msg: Rebooting post package update (via Ansible)
  when: updates.changed and reboot_required
