[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[influxdb]
base_url = "http://192.168.42.241:8086"
bucket_name = "machinestate"
channels_per_subprocess = 1000

[sources.data_writer]
file_max_items = 100000

[normalize]
workers = 3

[load]
delete_completed_jobs = true
raise_on_max_retries = 1
workers = 1
