[runtime]
dlthub_telemetry = false
log_level = "WARNING"

[influxdb]
base_url = "http://192.168.42.241:8086"
bucket_name = "machinestate"
channel_batch_size = 3

[sources.data_writer]
file_max_items = 100000

[normalize]
workers = 3

[load]
delete_completed_jobs = true
raise_on_max_retries = 1
workers = 1

[destination.filesystem]
layout = "{schema_name}/{table_name}/{YYYY}/{MM}/{DD}/{load_id}.{file_id}.{ext}"

[dev_influxdb.destination.filesystem]
bucket_url = "./dev-lakehouse-source-accelerator-influxdb/"
auto_mkdir = true

[influxdb.destination.filesystem]
bucket_url = "s3://prod-lakehouse-source-accelerator-influxdb/"
