---
# This instance supports running ELT scripts
- name: Configure Ingestion instance
  hosts: elt
  # roles:
  #   - role: robertdebock.logrotate
  #     become: true
  tasks:
    # ---------- UV & Python ----------
    - name: Check if uv exists
      stat:
        path: /usr/local/bin/uv
      register: stat_uv

    - name: Fetch uv installer
      ansible.builtin.get_url:
        url: https://astral.sh/uv/0.6.6/install.sh
        dest: /tmp/uv-install.sh
      when: not stat_uv.stat.exists

    - name: Execute uv installer
      become: true
      shell: env UV_UNMANAGED_INSTALL=/usr/local/bin sh /tmp/uv-install.sh
      when: not stat_uv.stat.exists

    - name: Remove uv installer script
      file:
        path: /tmp/uv-install.sh
        state: absent
      when: not stat_uv.stat.exists

    - name: Find compatible Python version
      ansible.builtin.command: uv python find --quiet "{{ elt_uv_python_version }}"
      ignore_errors: true
      register: uv_python_find

    - name: Ensure Python is installed
      ansible.builtin.command: uv python install "{{ elt_uv_python_version }}"
      when: uv_python_find.rc != 0

    # ---------- AWS S3 ----------
    - name: Ensure S3 configuration directory exists
      ansible.builtin.file:
        path: "{{ ansible_env['HOME'] }}/.aws"
        state: directory
        mode: "u=rwx,g=rx,o=rx"

    - name: Ensure S3 config file is absent
      ansible.builtin.file:
        path: "{{ ansible_env['HOME'] }}/.aws/config"
        state: absent

    - name: Ensure AWS configuration is present
      ansible.builtin.copy:
        dest: "{{ ansible_env['HOME'] }}/.aws/credentials"
        content: |+
          [default]
          endpoint = {{ s3_endpoint }}
          request_checksum_calculation = when_required
          region = local-01
          aws_access_key_id = {{ s3_access_key_id }}
          aws_secret_access_key = {{ s3_access_secret }}
        mode: "u=rw,o=r,g=r"

    # ---------- secrets ----------
    - name: Ensure secrets directories exist
      become: true
      ansible.builtin.file:
        path: "{{ elt_secrets_root_dir }}/{{ warehouse.name }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
      with_items: "{{ elt_warehouses }}"
      loop_control:
        loop_var: warehouse

    - name: Generate secrets
      become: true
      no_log: true
      ansible.builtin.template:
        src: ./secrets/envvars.j2
        dest: "{{ elt_secrets_root_dir }}/{{ warehouse.name }}/envvars"
        mode: "u=rwx,g=r,o=r"
      with_items: "{{ elt_warehouses }}"
      loop_control:
        loop_var: warehouse

    # # ---------- Cron tasks ----------
    - name: Ensure cron scripts directory exists
      ansible.builtin.file:
        path: "{{ elt_cron_root_dir }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"

    - name: Create/update ELT cron script template
      ansible.builtin.template:
        src: ./cron/elt_task.sh.j2
        dest: "{{ elt_cron_root_dir }}/elt_task.sh"
        mode: "u=rwx,g=rx,o=rx"

    - name: Ensure cron jobs exist
      ansible.builtin.cron:
        name: "{{ warehouse.sources[0].name }}"
        state: "{{ warehouse.sources[0].state | default('present') }}"
        hour: "{{ warehouse.sources[0].hour }}"
        minute: "{{ warehouse.sources[0].minute }}"
        job: >
          ELT_GIT_REF=multiple-warehouses {{ elt_cron_root_dir }}/elt_task.sh
          https://github.com/{{ warehouse.github_org }}/{{ warehouse.github_repo }}.git
          {{ elt_git_clone_dir }}/{{ warehouse.github_org }}/{{ warehouse.github_repo }}
          {{ warehouse.sub_dir }}/extract_load/statusdisplay
          {{ warehouse.sub_dir }}/transform/{{ warehouse.name }}
          --select 'staging/statusdisplay+'
      with_items: "{{ elt_warehouses }}"
      loop_control:
        loop_var: warehouse

        # job: >
        #   {{ elt_cron_root_dir }}/elt_task.sh
        #     https://github.com/{{ warehouse.github_org }}/{{ warehouse.github_repo }}
        #     {{ elt_git_clone_dir }}/{{ warehouse.github_org }}/{{ warehouse.github_repo }}
        #     {{ warehouse.sub_dir }}/extract_load/statusdisplay
    # # ---------- statusdisplay ----------
    # - name: Ensure statusdisplay cron logs directory exists
    #   become: true
    #   ansible.builtin.file:
    #     path: "{{ elt_elt_statusdisplay_log_dir }}"
    #     state: directory
    #     recurse: true
    #     mode: "u=rwx,g=rx,o=rx"
    #     owner: 1000
    #     group: 1000

    # - name: Ensure daily statusdisplay ingest job exists
    #   ansible.builtin.cron:
    #     name: "Statusdisplay ingest"
    #     state: "{{ elt_cron_state | default('present') }}"
    #     minute: "15"
    #     hour: "0"
    #     job: >
    #       {{ elt_elt_cron_scripts_dir }}/elt_task.sh
    #         {{ elt_elt_extract_root }}/statusdisplay"
    #         {{ elt_elt_dbt_root }} --select 'staging/statusdisplay+' >
    #         {{ elt_elt_statusdisplay_log_dir }}/elt-$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).log 2>&1"

    # # ---------- Opralog ----------
    # - name: Ensure Opralog cron logs directory exists
    #   become: true
    #   ansible.builtin.file:
    #     path: "{{ elt_elt_opralogweb_log_dir }}"
    #     state: directory
    #     recurse: true
    #     mode: "u=rwx,g=rx,o=rx"
    #     owner: 1000
    #     group: 1000

    # - name: Ensure daily Opralog ingest job exists
    #   ansible.builtin.cron:
    #     name: "Opralog ingest"
    #     state: "{{ elt_cron_state | default('present') }}"
    #     minute: "10"
    #     hour: "2"
    #     job: >
    #       {{ elt_elt_cron_scripts_dir }}/elt_task.sh
    #         {{ elt_elt_extract_root }}/opralogweb
    #         {{ elt_elt_dbt_root }} --select 'staging/opralogweb+' >
    #         {{ elt_elt_opralogweb_log_dir }}/elt-$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).log 2>&1"

    # # ---------- Electricity ----------
    # - name: Ensure Electricity SharePoint cron logs directory exists
    #   become: true
    #   ansible.builtin.file:
    #     path: "{{ elt_elt_electricity_sharepoint_log_dir }}"
    #     state: directory
    #     recurse: true
    #     mode: "u=rwx,g=rx,o=rx"
    #     owner: 1000
    #     group: 1000

    # - name: Ensure Electricity SharePoint ingest job exists
    #   ansible.builtin.cron:
    #     name: "Electricity SharePoint ingest"
    #     state: "{{ elt_cron_state | default('present') }}"
    #     minute: "05"
    #     hour: "*"
    #     job: >
    #       {{ elt_elt_cron_scripts_dir }}/elt_task.sh
    #         {{ elt_elt_extract_root }}/electricity_sharepoint
    #         {{ elt_elt_dbt_root }} --select 'staging/electricity_sharepoint+' >
    #         {{ elt_elt_electricity_sharepoint_log_dir }}/elt-$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).log 2>&1
