---
- name: Destroy all cloud VMs listed in the inventory file
  hosts: localhost
  gather_facts: false
  vars:
    vms_to_delete: "{{ groups.keys() | reject('==', 'all') | reject('==', 'ungrouped') }}"
  tasks:
    - ansible.builtin.debug:
        msg: "The following VMs will be deleted: {{ vms_to_delete }}"
    - pause:
        prompt: "Do you want to continue (yes/no)?"
      register: pause_info
      delegate_to: localhost
    - ansible.builtin.debug:
        msg: "{{ pause_info }}"
    - name: Ensure cloud server(s) are deleted
      openstack.cloud.server:
        cloud: "{{ openstack_cloud_name }}"
        name: "{{ server_name }}"
        timeout: 200
        state: absent
      with_items: "{{ vms_to_delete }}"
      loop_control:
        loop_var: server_name
      when: pause_info.user_input == "yes"
