name: End-to-end tests for elt-common package
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/elt-common_e2e_tests.yml"
      - "infra/local/**"
      - "pipelines/elt-common/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/elt-common_e2e_tests.yml"
      - "infra/local/**"
      - "pipelines/elt-common/**"
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or tag to checkout"
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ----------- Checkout -----------
      - name: Checkout using push or pull_request event
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/checkout@v4
      - name: Checkout using ref (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      # --------------------------------

      - name: Bring up Lakekeeper & dependent services
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "pipelines/elt-common/tests/docker-compose.yml"

      - name: Run pipeline-common end-to-end tests
        run: >
          docker compose
          --file tests/docker-compose.yml
          run
          --env CI=1
          python-uv
          uv run pytest --durations-min=0.5 --exitfirst tests/e2e_tests --cache-clear
        working-directory: ./pipelines/elt-common
