name: Test ingest and transform steps against REST catalog
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/rest-catalog-tests.yml"
      - "infra/ansible/roles/lakekeeper/files/bootstrap-warehouse.py"
      - "elt-common/**"
      - "warehouses/facility_ops_landing/extract_load/opralogweb/**"
      - "warehouses/facility_ops/transform/**"
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - ".github/workflows/rest-catalog-tests.yml"
      - "infra/ansible/roles/lakekeeper/files/bootstrap-warehouse.py"
      - "elt-common/**"
      - "warehouses/facility_ops_landing/extract_load/opralogweb/**"
      - "warehouses/facility_ops/transform/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
    github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.13
  UV_VERSION: latest

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bring up Docker Compose services
        uses: hoverkraft-tech/compose-action@v2.5.0
        with:
          compose-file: infra/local/docker-compose.yml
          up-flags: --wait --wait-timeout 300
          down-flags: --volumes --remove-orphans

      - name: Add adp-router to /etc/hosts
        shell: bash -l {0}
        run: |
          echo "127.0.0.1    adp-router" | sudo tee -a /etc/hosts

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install script dependencies
        shell: bash -l {0}
        run: |
          uv sync --active --script warehouses/facility_ops_landing/ingest/accelerator/opralogweb/opralogweb.py

      - name: Install ingest test dependencies
        shell: bash -l {0}
        run: |
          uv pip install --group dev .
        working-directory: elt-common

      - name: Run ingest test against REST catalog
        shell: bash -l {0}
        run: |
          pytest --durations-min=0.5 --exitfirst --catalog-type=rest tests --cache-clear
        working-directory: warehouses/facility_ops_landing/ingest/accelerator/opralogweb

      - name: Install dbt test dependencies
        shell: bash -l {0}
        run: |
          uv pip install --requirements requirements/requirements.txt
          dbt clean
          dbt deps
        working-directory: warehouses/facility_ops/transform

      - name: Run dbt tests
        shell: bash -l {0}
        run: |
          # setup
          dbt run --select tag:unit_test_setup
          # run tests
          dbt test --resource-type unit_test
        working-directory: warehouses/facility_ops/transform

      - name: Remove adp-router from /etc/hosts
        if: always()
        shell: bash -l {0}
        run: |
          sudo sed -i -e '/adp-router/d' /etc/hosts
