name: isis
version: "1.0.0"

profile: "spark"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["dbt_macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +materialized: "table"
  isis:
    # The full schema name of the final tables is "{target_schema}_"{custom_schema}"
    #   - 'target_schema' is defined in profiles.yml
    #   - 'custom_schema' is defined for each collection of models below
    # See https://docs.getdbt.com/docs/build/custom-schemas
    facility:
      +schema: "facility"
