spark:
  target: prod
  outputs:
    prod:
      type: spark
      method: session
      schema: "{{ env_var('DBT_SPARK_SCHEMA') }}"
      host: NA
      server_side_parameters:
        "spark.sql.catalog.isis": "org.apache.iceberg.spark.SparkCatalog"
        "spark.sql.catalog.isis.type": "rest"
        "spark.sql.catalog.isis.uri": "{{ env_var('DBT_SPARK_ICEBERG_CATALOG_URI') }}"
        "spark.sql.catalog.isis.authentication.type": "NONE"
        "spark.sql.catalogImplementation": "in-memory"
        "spark.sql.defaultCatalog": "{{ env_var('DBT_SPARK_DEFAULT_CATALOG') }}"
        "spark.master": "{{ env_var('DBT_SPARK_MASTER') }}"
        "spark.blockManager.port": "{{ env_var('DBT_SPARK_BLOCKMANAGER_PORT') }}"
        "spark.broadcast.port": "{{ env_var('DBT_SPARK_BROADCAST_PORT') }}"
        "spark.driver.port": "{{ env_var('DBT_SPARK_DRIVER_PORT') }}"
        "spark.fileserver.port": "{{ env_var('DBT_SPARK_FILESERVER_PORT') }}"
        "spark.ui.reverseProxy": "true"
        "spark.ui.reverseProxyUrl": "{{ env_var('DBT_SPARK_REVERSE_PROXY_URL') }}"
        "spark.ui.showConsoleProgress": "false"
        "spark.cores.max": "{{ env_var('DBT_SPARK_CORES_MAX', '8') }}"
        "spark.executor.memory": "{{ env_var('DBT_SPARK_EXECUTOR_MEMORY', '16g') }}"
        "spark.jars.packages": "org.apache.hadoop:hadoop-aws:3.3.4,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1,org.apache.iceberg:iceberg-aws-bundle:1.6.1,org.projectnessie.nessie-integrations:nessie-spark-extensions-3.5_2.12:0.91.3"
        "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
        "spark.hadoop.fs.s3a.endpoint": "{{ env_var('DBT_SPARK_S3_ENDPOINT') }}"
        "spark.hadoop.fs.s3a.endpoint.region": "eu-west-1"
        "spark.hadoop.fs.s3a.path.style.access": "true"
        "spark.hadoop.fs.s3a.access.key": "{{ env_var('DBT_ENV_SECRET_SPARK_S3_ACCESS_KEY') }}"
        "spark.hadoop.fs.s3a.secret.key": "{{ env_var('DBT_ENV_SECRET_SPARK_S3_SECRET') }}"
        "spark.sql.session.timeZone": "UTC"
        "spark.sql.repl.eagerEval.enabled": "true"
        "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions"
