spark:
  target: isis_catalog
  outputs:
    isis_catalog:
      type: spark
      method: session
      schema: "{{ env_var('DBT_SPARK_SCHEMA', 'analytics') }}"
      host: NA
      server_side_parameters:
        # This configuration assumes a spark-defaults.conf can be found containing the
        # catalog configuration and secrets.
        # The directory containing spark-defaults.conf can be set using the SPARK_CONF_DIR environment variable
        "spark.sql.defaultCatalog": "isis"
