spark:
  target: prod
  outputs:
    prod:
      type: spark
      method: session
      schema: "{{ env_var('DBT_SPARK_SCHEMA', 'analytics') }}"
      host: NA
      server_side_parameters:
        "spark.sql.defaultCatalog": "{{ env_var('DBT_SPARK_DEFAULT_CATALOG', 'isis') }}"
